import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant';
import type { NavigationTree } from '@/@types/navigation';

const navigationConfig: NavigationTree[] = [
    // Super Admin Menu
    {
        key: 'superAdmin',
        path: '/home',
        title: 'Super Admin',
        translateKey: '',
        icon: 'singleMenu',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [], // Define authority roles here
        subMenu: [

            {
                key: 'superAdmin.dashboard',
                path: '/business-owner/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.superAdmin.dashboard',
                icon: 'singleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },

            {
                key: 'superAdmin.businessManagement',
                path: '/business',
                title: 'Business Management',
                translateKey: 'nav.superAdmin.businessManagement',
                icon: 'business',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'superAdmin.businessManagement',
                        path: '/business',
                        title: 'Business List',
                        translateKey: 'nav.superAdmin.businessManagement',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'superAdmin.addBusiness',
                        path: '/add-business',
                        title: 'Add Business',
                        translateKey: 'nav.superAdmin.addBusiness',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'superAdmin.driverManagement',
                path: '/driver',
                title: 'Driver Management',
                translateKey: 'nav.superAdmin.driverManagement',
                icon: 'driver',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'superAdmin.driverManagement',
                        path: '/Driver',
                        title: 'Drivers List',
                        translateKey: 'nav.superAdmin.driverManagement',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'superAdmin.addDriver',
                        path: '/add-driver',
                        title: 'Add Driver',
                        translateKey: 'nav.superAdmin.addDriver',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
                        {
                key: 'superAdmin.payments',
                path: '/payment-histpry',
                title: 'Payments',
                translateKey: 'nav.superAdmin.payments',
                icon: 'payments',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'superAdmin.payments',
                        path: '/income-payments',
                        title: 'Incoming Payments',
                        translateKey: 'nav.superAdmin.payments',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'superAdmin.payments1',
                        path: '/payment-history',
                        title: 'Payment History',
                        translateKey: 'nav.superAdmin.payments1',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'superAdmin.reports',
                path: '/super-admin/reports',
                title: 'Reports',
                translateKey: 'nav.superAdmin.reports',
                icon: 'report',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    // Business Owner Menu
    {
        key: 'businessOwner',
        path: '',
        title: 'Business Owner',
        translateKey: '',
        icon: 'business',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [], // Define authority roles here
        subMenu: [
            {
                key: 'businessOwner.dashboard',
                path: '/business-owner/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.businessOwner.dashboard',
                icon: 'singleMenu',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'businessOwner.business',
                path: '',
                title: 'Business Management',
                translateKey: 'nav.businessOwner.business',
                icon: 'business',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'businessOwner.businessProfile',
                        path: '/business-owner/business/profile',
                        title: 'Business Profile',
                        translateKey: 'nav.businessOwner.businessProfile',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'businessOwner.manageEmployees',
                        path: '/business-owner/business/employees',
                        title: 'Manage Employees',
                        translateKey: 'nav.businessOwner.manageEmployees',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'businessOwner.orders',
                path: '',
                title: 'Orders',
                translateKey: 'nav.businessOwner.orders',
                icon: 'order',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'businessOwner.activeOrders',
                        path: '/business-owner/orders/active',
                        title: 'Active Orders',
                        translateKey: 'nav.businessOwner.activeOrders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'businessOwner.completedOrders',
                        path: '/business-owner/orders/completed',
                        title: 'Completed Orders',
                        translateKey: 'nav.businessOwner.completedOrders',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
        ],
    },

    // Driver Menu
    {
        key: 'driver',
        path: '',
        title: 'Driver',
        translateKey: '',
        icon: 'driver',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [], // Define authority roles here
        subMenu: [
            {
                key: 'driver.dashboard',
                path: '/driver/dashboard',
                title: 'Dashboard',
                translateKey: 'nav.driver.dashboard',
                icon: 'dashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'driver.rides',
                path: '',
                title: 'Rides',
                translateKey: 'nav.driver.rides',
                icon: 'ride',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'driver.activeRides',
                        path: '/driver/rides/active',
                        title: 'Active Rides',
                        translateKey: 'nav.driver.activeRides',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'driver.completedRides',
                        path: '/driver/rides/completed',
                        title: 'Completed Rides',
                        translateKey: 'nav.driver.completedRides',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'driver.payments',
                path: '',
                title: 'Payments',
                translateKey: 'nav.driver.payments',
                icon: 'payments',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [],
                subMenu: [
                    {
                        key: 'driver.incomingPayments',
                        path: '/driver/payments/incoming',
                        title: 'Incoming Payments',
                        translateKey: 'nav.driver.incomingPayments',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                    {
                        key: 'driver.paymentHistory',
                        path: '/driver/payments/history',
                        title: 'Payment History',
                        translateKey: 'nav.driver.paymentHistory',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'driver.support',
                path: '/driver/support',
                title: 'Support',
                translateKey: 'nav.driver.support',
                icon: 'support',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
];

export default navigationConfig;
